name: Deploy React App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest code and build
        run: |
          cd /var/www/portfolio
          git pull
          npm install
          CI=false npm run build 